version: '3'

services:
 db:
  image: mysql
  environment:
   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
   MYSQL_DATABASE: elibrary
   MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  ports:
    - "3306:3306"
 api:
  image: php
  volumes:
   - ./php/:/var/www/html
  ports:
    - "80:80"
  depends_on:
    - db
  stdin_open: true
  tty: true
  