# 使用官方的 PHP 映像
FROM php:7.4-apache

# 設置環境變數
ARG ROOT_PASSWORD

# 設置 root 使用者的密碼
RUN echo "root:${ROOT_PASSWORD}" | chpasswd

# 安裝 PHP MySQL 擴展和其他必要工具
RUN apt-get update -y && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    wget \
    && docker-php-ext-install mysqli pdo pdo_mysql \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip

# 啟用 Apache mod_rewrite 模組
RUN a2enmod rewrite

# 安裝 Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# 設置工作目錄
WORKDIR /var/www/html/api

# 安裝 Slim 框架及其依賴項
RUN composer require --with-all-dependencies slim/slim:"4.*"
RUN composer require --with-all-dependencies slim/psr7
RUN composer require --with-all-dependencies selective/basepath

# 複製 php 目錄內容到容器中
COPY ./php/ /var/www/html

# 配置 Apache 允許 .htaccess 文件
RUN echo '<Directory /var/www/html>\n\
    AllowOverride All\n\
</Directory>' > /etc/apache2/conf-available/allow-override.conf \
    && a2enconf allow-override

# 開放端口
EXPOSE 80

# 設置卷
VOLUME ["/var/www/html"]

# 啟動 Apache 服務
CMD apache2-foreground